### ISSUE TITLE
Food HUD timers don't work on 1.19.2 (+ fix)

### ISSUE THREAD

**Issue by connery0** [kinghzrd/sol_valheim#1]
First of, thanks for updating this mod, we want to use it in a pack and it was a lifesaver

Unfortunately the food timers don't update live on 1.19.2, but when manually merging in the changes from this seperate fork it worked fine when testing. 
https://github.com/BehindTheScenery/sol_valheim

Please consider merging it in.
https://github.com/kinghzrd/sol_valheim/compare/hud-overhaul...BehindTheScenery:sol_valheim:master

(and a new curseforge build with the fixed javeFML version would be apreciated, because I didn't even have to change that when recompiling your mod from the repo)

**Comment by kinghzrd** [comment]
Hey. thanks for checking out this fork!

I went ahead and merged it in. I was initially going to try something different, ideally without breaking when installed with Lithium. Though, I never really got anything substantial done.

As for a new build and stuff, I'll get around to that once I finish the last few features and fixes I have in mind.
